/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MisPostulacionesRouteImport } from './routes/mis-postulaciones'
import { Route as VacantesRouteImport } from './routes/vacantes'
import { Route as AdminCandidatosRouteImport } from './routes/admin.candidatos'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminMensajesRouteImport } from './routes/admin.mensajes'
import { Route as AdminReportesRouteImport } from './routes/admin.reportes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPostulacionesRoute = MisPostulacionesRouteImport.update({
  id: '/mis-postulaciones',
  path: '/mis-postulaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const VacantesRoute = VacantesRouteImport.update({
  id: '/vacantes',
  path: '/vacantes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatosRoute = AdminCandidatosRouteImport.update({
  id: '/candidatos',
  path: '/candidatos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMensajesRoute = AdminMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/mis-postulaciones': typeof MisPostulacionesRoute
  '/vacantes': typeof VacantesRoute
  '/admin/candidatos': typeof AdminCandidatosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/admin/reportes': typeof AdminReportesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/mis-postulaciones': typeof MisPostulacionesRoute
  '/vacantes': typeof VacantesRoute
  '/admin/candidatos': typeof AdminCandidatosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/admin/reportes': typeof AdminReportesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/mis-postulaciones': typeof MisPostulacionesRoute
  '/vacantes': typeof VacantesRoute
  '/admin/candidatos': typeof AdminCandidatosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/admin/reportes': typeof AdminReportesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/mis-postulaciones'
    | '/vacantes'
    | '/admin/candidatos'
    | '/admin/dashboard'
    | '/admin/mensajes'
    | '/admin/reportes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/mis-postulaciones'
    | '/vacantes'
    | '/admin/candidatos'
    | '/admin/dashboard'
    | '/admin/mensajes'
    | '/admin/reportes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/mis-postulaciones'
    | '/vacantes'
    | '/admin/candidatos'
    | '/admin/dashboard'
    | '/admin/mensajes'
    | '/admin/reportes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MisPostulacionesRoute: typeof MisPostulacionesRoute
  VacantesRoute: typeof VacantesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-postulaciones': {
      id: '/mis-postulaciones'
      path: '/mis-postulaciones'
      fullPath: '/mis-postulaciones'
      preLoaderRoute: typeof MisPostulacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacantes': {
      id: '/vacantes'
      path: '/vacantes'
      fullPath: '/vacantes'
      preLoaderRoute: typeof VacantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidatos': {
      id: '/admin/candidatos'
      path: '/candidatos'
      fullPath: '/admin/candidatos'
      preLoaderRoute: typeof AdminCandidatosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mensajes': {
      id: '/admin/mensajes'
      path: '/mensajes'
      fullPath: '/admin/mensajes'
      preLoaderRoute: typeof AdminMensajesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCandidatosRoute: typeof AdminCandidatosRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMensajesRoute: typeof AdminMensajesRoute
  AdminReportesRoute: typeof AdminReportesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCandidatosRoute: AdminCandidatosRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMensajesRoute: AdminMensajesRoute,
  AdminReportesRoute: AdminReportesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MisPostulacionesRoute: MisPostulacionesRoute,
  VacantesRoute: VacantesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
