/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RhRouteImport } from './routes/rh'
import { Route as RhIndexRouteImport } from './routes/rh.index'
import { Route as RhCandidatosRouteImport } from './routes/rh.candidatos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RhRoute = RhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const RhIndexRoute = RhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RhRoute,
} as any)
const RhCandidatosRoute = RhCandidatosRouteImport.update({
  id: '/candidatos',
  path: '/candidatos',
  getParentRoute: () => RhRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rh': typeof RhRouteWithChildren
  '/rh/candidatos': typeof RhCandidatosRoute
  '/rh/': typeof RhIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rh/candidatos': typeof RhCandidatosRoute
  '/rh': typeof RhIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rh': typeof RhRouteWithChildren
  '/rh/candidatos': typeof RhCandidatosRoute
  '/rh/': typeof RhIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rh' | '/rh/candidatos' | '/rh/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rh/candidatos' | '/rh'
  id: '__root__' | '/' | '/rh' | '/rh/candidatos' | '/rh/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RhRoute: typeof RhRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh': {
      id: '/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/': {
      id: '/rh/'
      path: '/'
      fullPath: '/rh/'
      preLoaderRoute: typeof RhIndexRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/candidatos': {
      id: '/rh/candidatos'
      path: '/candidatos'
      fullPath: '/rh/candidatos'
      preLoaderRoute: typeof RhCandidatosRouteImport
      parentRoute: typeof RhRoute
    }
  }
}

interface RhRouteChildren {
  RhCandidatosRoute: typeof RhCandidatosRoute
  RhIndexRoute: typeof RhIndexRoute
}

const RhRouteChildren: RhRouteChildren = {
  RhCandidatosRoute: RhCandidatosRoute,
  RhIndexRoute: RhIndexRoute,
}

const RhRouteWithChildren = RhRoute._addFileChildren(RhRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RhRoute: RhRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
