/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminCandidatosRouteImport } from './routes/admin.candidatos'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminReportesRouteImport } from './routes/admin.reportes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatosRoute = AdminCandidatosRouteImport.update({
  id: '/admin/candidatos',
  path: '/admin/candidatos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/admin/reportes',
  path: '/admin/reportes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/candidatos': typeof AdminCandidatosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reportes': typeof AdminReportesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/candidatos': typeof AdminCandidatosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reportes': typeof AdminReportesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/candidatos': typeof AdminCandidatosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reportes': typeof AdminReportesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/candidatos' | '/admin/dashboard' | '/admin/reportes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/candidatos' | '/admin/dashboard' | '/admin/reportes'
  id:
    | '__root__'
    | '/'
    | '/admin/candidatos'
    | '/admin/dashboard'
    | '/admin/reportes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCandidatosRoute: typeof AdminCandidatosRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminReportesRoute: typeof AdminReportesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidatos': {
      id: '/admin/candidatos'
      path: '/admin/candidatos'
      fullPath: '/admin/candidatos'
      preLoaderRoute: typeof AdminCandidatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/admin/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCandidatosRoute: AdminCandidatosRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminReportesRoute: AdminReportesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
